<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <VersionPrefix>0.14.0</VersionPrefix>
    <VersionSuffix>beta</VersionSuffix>
    <Title>Caribou</Title>
    <Description>Description of Caribou</Description>
    <RhinoPluginType>gha</RhinoPluginType><!-- Tells MacOS VS to rename to gha -->
    <TargetExt>.gha</TargetExt><!-- Tells Windows VS to rename to gha -->
    <RhinoMacLauncher>/Applications/Rhino 8.app</RhinoMacLauncher>
    <Configurations>Debug;Release;Debug (v6)</Configurations>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageProjectUrl>https://philipbelesky.com</PackageProjectUrl>
    <RepositoryUrl>https://github.com/philipbelesky/Caribou</RepositoryUrl>
    <AssemblyVersion>0.14.0.0</AssemblyVersion>
    <FileVersion>0.14.0.0</FileVersion>
    <Version>0.14.0-beta</Version>
  </PropertyGroup>

  <!--NUGET-->
  <ItemGroup>
    <PackageReference Include="Grasshopper" Version="8.4.24044.14305" IncludeAssets="compile;build" />
    <PackageReference Include="Hsluv" Version="1.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
    <PackageReference Include="System.ServiceModel.Syndication" Version="8.0.0" />
  </ItemGroup>

  <!--LOCALLY REFERENCED ASSEMBLIES (Only needed if Grasshopper package doesn't include them)-->
  <ItemGroup Condition="$([MSBuild]::IsOSPlatform(Windows))">
    <Reference Include="Eto" Condition="!Exists('$(PkgGrasshopper)\lib\net7.0\Eto.dll')">
      <HintPath>C:\Program Files\Rhino 8\System\Eto.dll</HintPath>
    </Reference>
    <Reference Include="Rhino.UI" Condition="!Exists('$(PkgGrasshopper)\lib\net7.0\Rhino.UI.dll')">
      <HintPath>C:\Program Files\Rhino 8\System\Rhino.UI.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup Condition="$([MSBuild]::IsOSPlatform(OSX))">
    <Reference Include="Eto" Condition="!Exists('$(PkgGrasshopper)\lib\net7.0\Eto.dll')">
      <HintPath>/Applications/Rhino 8.app/Contents/Frameworks/Eto.dll</HintPath>
    </Reference>
    <Reference Include="Rhino.UI" Condition="!Exists('$(PkgGrasshopper)\lib\net7.0\Rhino.UI.dll')">
      <HintPath>/Applications/Rhino 8.app/Contents/Frameworks/RhinoCommon.framework/Rhino.UI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <!--RESOURCES FILES-->
  <ItemGroup>
    <Compile Update="Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <!--BUILDS-->
  <!--Make Unit-Testable DLLs-->
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform(Windows))">
    <PostBuildEvent>
      echo f | xcopy "$(TargetDir)Caribou.gha" "$(SolutionDir)Caribou\bin\ForTests\Caribou.dll" /y /i
    </PostBuildEvent>
  </PropertyGroup>
  <PropertyGroup Condition="$([MSBuild]::IsOSUnixLike())">
    <PostBuildEvent>
      mkdir -p "$(SolutionDir)Caribou/bin/ForTests" &amp;&amp; cp "$(TargetDir)Caribou.gha" "$(SolutionDir)Caribou/bin/ForTests/Caribou.dll"
    </PostBuildEvent>
  </PropertyGroup>
  <!-- Don't provide pdb file for release builds -->
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>


</Project>