<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <TestProjectType>UnitTest</TestProjectType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grasshopper" Version="8.4.24044.14305" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
  </ItemGroup>

  <!-- Both the project and assembly reference seem to be required for tests to not skip -->
  <ItemGroup>
    <ProjectReference Include="..\Caribou\Caribou.csproj">
      <Private>true</Private>
    </ProjectReference>
  </ItemGroup>

  <!--Make Unit-Testable DLLs (Caribou, as a referenced project, is copied over as a gha -->
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform(Windows))">
    <PostBuildEvent>
      echo f | xcopy "$(TargetDir)Caribou.gha" "$(TargetDir)Caribou.dll" /y /i
    </PostBuildEvent>
  </PropertyGroup>
  <PropertyGroup Condition="$([MSBuild]::IsOSUnixLike())">
    <PostBuildEvent>
      cp "$(TargetDir)Caribou.gha" "$(TargetDir)Caribou.dll"
    </PostBuildEvent>
  </PropertyGroup>

</Project>
